version: '3'
services:
  app:
    image: golang:1.21.4
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - 8080:8080
    tty: true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
