version: '3'
services:
  app:
    depends_on:
      - db
    image: golang:1.21.4
    volumes: 
      - .:/code
    working_dir: /code
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASS: ${POSTGRES_PASSWORD}
      DATABASE_NAME: app
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_PASS: ${ADMIN_PASS}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
      
    ports:
      - 8080:8080
    tty: true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
