version: '3'
services:
  app:
    image: golang:1.21.4
    volumes:
      - .:/code
    working_dir: /code
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_NAME: app
      ALLOWED_ORIGIN: https://yukizemi.online
      ADMIN_NAME: hiroshijp
      ADMIN_PASS: password
    ports:
      - 8080:8080
    tty: true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
